Document: sflowtool
Title: Debian sflowtool Manual
Author: <insert document author here>
Abstract: This manual describes what sflowtool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sflowtool/sflowtool.sgml.gz

Format: postscript
Files: /usr/share/doc/sflowtool/sflowtool.ps.gz

Format: text
Files: /usr/share/doc/sflowtool/sflowtool.text.gz

Format: HTML
Index: /usr/share/doc/sflowtool/html/index.html
Files: /usr/share/doc/sflowtool/html/*.html
